import "./globals.css";
import type { Metadata } from "next";
import { Source_Serif_4 } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";
const source_Serif_4 = Source_Serif_4({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "GoVan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={source_Serif_4.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
